require 'rubygems'
require 'cucumber'
require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:features) do |t|
  t.profile = 'default'
end

task :default => :features

# directory "temp"
# file "hello.temp" => "temp" do
#   sh "echo 'Hello' >> 'tmp/hello.tmp'"
# end
